"""gate_91_verilator_codecov — ADR-0063 V5: Verilator line+toggle code coverage baseline.

Asserts the committed baseline report (flow/coverage/verilator/codecov_report.json,
regenerated by run_cov.sh) for the modules THIS DUT+stimulus is responsible for — the
vector + scalar-F datapath (vexu, fexu), which the phase_22 regression exercises. The
NPU-offload (mat_engine/dma/CQ/axil_regs) and host-scalar (bmu/csr/idu/div/pmp/trigger)
paths are under-covered here BY DESIGN (they need the tflm/CQ and host-rv32imc harnesses)
and are the V5 backlog — not gated at this DUT.

Authority note (G1): code coverage is COMPLETENESS, not correctness — every firmware run
here is Spike-lockstep verified in phase_22.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
REPORT = ROOT / "flow/coverage/verilator/codecov_report.json"

# (module, min line %, min toggle %) for the vector/FP datapath this run owns.
OWNED = [("vexu.v", 95, 95), ("fexu.v", 90, 90)]
# under-covered here by design — tracked so the report can't silently claim them.
BACKLOG_STIMULUS = {
    "mat_engine.v": "tflm/CQ harness (gate_50/82/phase_23)",
    "npu_dma.v": "tflm/offload harness (gate_29/51)",
    "npu_axil_regs.v": "CQ/CSR harness (phase_21)",
    "bmu.v": "host rv32imc Zba/Zbb/Zbs tests (phase_03/04)",
    "csr.v": "host CSR/trap tests (phase_03/04)",
    "idu.v": "host + full-decode tests",
}


def _pct(pair):
    c, t = pair
    return 100.0 * c / t if t else 0.0


def test_report_exists():
    assert REPORT.exists(), "run flow/coverage/verilator/run_cov.sh to generate the baseline"


def test_owned_datapath_coverage():
    d = json.loads(REPORT.read_text())["per_file"]
    for mod, lmin, tmin in OWNED:
        assert mod in d, f"{mod} missing from coverage report"
        lp, tp = _pct(d[mod]["line"]), _pct(d[mod]["toggle"])
        assert lp >= lmin, f"{mod} line coverage {lp:.0f}% < {lmin}% (regressed)"
        assert tp >= tmin, f"{mod} toggle coverage {tp:.0f}% < {tmin}% (regressed)"


def test_backlog_modules_are_acknowledged():
    # honest-界: the low-coverage modules here are a KNOWN backlog needing other
    # stimulus — asserted present so a future full-merge report supersedes cleanly.
    d = json.loads(REPORT.read_text())["per_file"]
    for mod in BACKLOG_STIMULUS:
        assert mod in d, f"{mod} missing (expected in the DUT even if under-covered)"
