"""gate_90_isa_coverage — ADR-0063 V1: instruction-coverage tracker + baseline.

Two checks, both fast/deterministic (no sim; the full log collection is
flow/coverage/collect.sh):
  1. Tool correctness: the ISA-coverage ingester parses Spike disasm lines, normalizes
     pseudos to their base op, buckets by extension, and — critically — gives NO credit
     for hitting an excluded scope-cut op (green-wash guard G7).
  2. Baseline thresholds on the committed report (flow/coverage/isa_cov_report.json,
     regenerated by collect.sh): scalar ISA fully exercised, Zve32x at/above baseline,
     exclusion ledger frozen (G6), no excluded op credited.

Authority note (G1): this is COMPLETENESS (did we exercise the encoding), NOT correctness
— every test counted here is itself Spike-lockstep verified elsewhere.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "flow/v2_pipeline/lib"))
import isa_cov  # noqa: E402

REPORT = ROOT / "flow/coverage/isa_cov_report.json"
SCALAR_FULL = ("i", "m", "f", "zba", "zbb", "zbs", "zicond", "zifencei")
ZVE32X_BASELINE = 181            # covered / 261 in-scope as of 2026-07-06 (ratchet up only)
EXCLUSION_COUNT = 32             # frozen scope-cut ledger (strided/indexed/ff/vlm/whole-reg)


def test_scope_ssot_shape():
    scope = isa_cov.build_scope()
    assert len(scope["zve32x"]) == 261, "Zve32x SSOT size drift — update baseline intentionally"
    assert len(isa_cov.build_exclusions()) == EXCLUSION_COUNT, "exclusion ledger changed (G6)"


def test_ingester_parses_and_normalizes():
    # synthetic Spike disasm lines: disasm (PC after colon) vs commit (priv digit) must differ
    sample = "\n".join([
        "core   0: 0x80000000 (0x20000293) li      t0, 512",           # -> addi
        "core   0: 3 0x80000000 (0x20000293) x5  0x00000200",          # commit: ignored
        "core   0: 0x80000004 (0x0c057357) vsetvli t1, a0, e8, m1",    # vsetvli
        "core   0: 0x80000008 (0x5e03c257) vmv.v.x v4, t2",            # vmv.v.x
        "core   0: 0x8000000c (0x3002a073) csrs    mstatus, t0",       # -> csrrs
    ])
    p = Path(isa_cov.__file__).parent / "_gate90_sample.log"
    p.write_text(sample)
    try:
        hits, _ = isa_cov.ingest([p])
    finally:
        p.unlink()
    assert hits.get("addi") == 1, "li must normalize to addi"
    assert hits.get("csrrs") == 1, "csrs must normalize to csrrs"
    assert "vsetvli" in hits and "vmv.v.x" in hits
    assert "x5" not in hits and "li" not in hits, "commit line / pseudo must not leak"


def test_excluded_op_gets_no_credit():
    # hitting a scope-cut op must be flagged, never credited (G7)
    scope, excl = isa_cov.build_scope(), isa_cov.build_exclusions()
    hits = {"vlse32.v": 3, "vadd.vv": 1}          # vlse32.v is excluded (strided)
    rows, surprises, excl_hit = isa_cov.report(hits, scope, excl)
    assert "vlse32.v" in excl_hit, "excluded op must be reported as hit-without-credit"
    zrow = next(r for r in rows if r[0] == "zve32x")
    assert "vlse32.v" not in scope["zve32x"], "excluded op must not be in the denominator"


def test_baseline_report_thresholds():
    assert REPORT.exists(), "run flow/coverage/collect.sh to generate the baseline report"
    d = json.loads(REPORT.read_text())
    for ext in SCALAR_FULL:
        pe = d["per_ext"][ext]
        assert pe["covered"] == pe["in_scope"], f"{ext} regressed below 100% ({pe})"
    z = d["per_ext"]["zve32x"]
    assert z["covered"] >= ZVE32X_BASELINE, f"Zve32x coverage regressed: {z['covered']} < {ZVE32X_BASELINE}"
    assert d["excluded"] == EXCLUSION_COUNT, "exclusion ledger drifted (G6)"
    assert not d["excluded_hit"], f"excluded ops were hit + would be credited: {d['excluded_hit']}"
