"""gate_91_verilator_codecov — ADR-0063 V5: Verilator line+toggle code coverage baseline.

Asserts the committed baseline report (flow/coverage/verilator/codecov_report.json,
regenerated by run_cov.sh) for the modules THIS DUT+stimulus is responsible for — the
vector + scalar-F datapath (vexu, fexu), which the phase_22 regression exercises. The
NPU-offload (mat_engine/dma/CQ/axil_regs) and host-scalar (bmu/csr/idu/div/pmp/trigger)
paths are under-covered here BY DESIGN (they need the tflm/CQ and host-rv32imc harnesses)
and are the V5 backlog — not gated at this DUT.

Authority note (G1): code coverage is COMPLETENESS, not correctness — every firmware run
here is Spike-lockstep verified in phase_22.
"""
import json
import shutil
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
REPORT = ROOT / "flow/coverage/verilator/codecov_report.json"

# Combined 3-DUT report (vector+tflm+host): line=union effective, toggle=per-owning DUT.
# (module, min line %, min toggle %) — the modules covered by their owning harness.
OWNED = [("vexu.v", 95, 95), ("fexu.v", 90, 90),
         ("mat_engine.v", 70, 85), ("npu_dma.v", 70, 50),
         ("npu_axil_regs.v", 55, 0), ("core.v", 65, 0), ("div.v", 70, 0),
         ("alu.v", 95, 95), ("lsu.v", 95, 95),
         ("bmu.v", 90, 90), ("idu.v", 80, 80)]     # V5 backlog #2 closed (Zb* + CSR/decode)
# remaining hard residuals — documented, not gated (feature-limited or non-deterministic).
BACKLOG_STIMULUS = {
    "csr.v": "PMP/trigger-CSR + perf-counter lines (documented-limited/non-deterministic)",
    "cdec.v": "compressed-decode corner tests",
    "pmp.v": "PMP (bypass, documented-limited — waiver candidate)",
    "trigger.v": "debug-trigger (bypass, documented-limited — waiver candidate)",
    "npu_axil_regs.v": "error-ladder paths (gate_29/38/47/54 — V5 backlog #3)",
}


def _pct(pair):
    c, t = pair
    return 100.0 * c / t if t else 0.0


def test_report_exists():
    assert REPORT.exists(), "run flow/coverage/verilator/run_cov.sh to generate the baseline"


def test_owned_datapath_coverage():
    d = json.loads(REPORT.read_text())["per_file"]
    for mod, lmin, tmin in OWNED:
        assert mod in d, f"{mod} missing from coverage report"
        lp, tp = _pct(d[mod]["line"]), _pct(d[mod]["toggle"])
        assert lp >= lmin, f"{mod} line coverage {lp:.0f}% < {lmin}% (regressed)"
        assert tp >= tmin, f"{mod} toggle coverage {tp:.0f}% < {tmin}% (regressed)"


@pytest.mark.skipif(not shutil.which("verilator"), reason="no verilator — not-run")
@pytest.mark.parametrize("phase", ["phase_03_21_isacov_bmu", "phase_03_22_isacov_csr"])
def test_backlog2_closure_host_lockstep(phase):
    # G2: the bmu (Zba/Zbb/Zbs) and csr (CSR+trap) closure firmwares that lifted
    # bmu 6%->94% / idu 49%->86% are DUT-verified vs Spike, not coverage-only.
    d = ROOT / "flow/v2_pipeline" / phase
    subprocess.run(["make", "-C", str(d), "lockstep.log"], capture_output=True, text=True)
    assert "PASS" in (d / "lockstep.log").read_text(), f"{phase} lockstep not PASS"


def test_backlog_modules_are_acknowledged():
    # honest-界: the low-coverage modules here are a KNOWN backlog needing other
    # stimulus — asserted present so a future full-merge report supersedes cleanly.
    d = json.loads(REPORT.read_text())["per_file"]
    for mod in BACKLOG_STIMULUS:
        assert mod in d, f"{mod} missing (expected in the DUT even if under-covered)"
