+define+SYNTHESIS
+incdir+../../../design/cpu_m1/rtl
../../../design/cpu_m1/rtl/rfu.v
../../../design/cpu_m1/rtl/alu.v
../../../design/cpu_m1/rtl/idu.v
../../../design/cpu_m1/rtl/ifu.v
../../../design/cpu_m1/rtl/lsu.v
../../../design/cpu_m1/rtl/csr.v
../../../design/cpu_m1/rtl/mul.v
../../../design/cpu_m1/rtl/div.v
../../../design/cpu_m1/rtl/forward.v
../../../design/cpu_m1/rtl/hazard.v
../../../design/cpu_m1/rtl/bp.v
../../../design/cpu_m1/rtl/ras.v
../../../design/cpu_m1/rtl/cdec.v
../../../design/cpu_m1/rtl/core.v
../../../design/cpu_m1/rtl/cpu_m1_top.v
../../../design/cpu_m1/rtl/axil_bridge.v
../../../design/cpu_m1/rtl/cpu_m1_axil_top.v
../../../design/cpu_m1/soc/axil_bootrom.v
../../../design/cpu_m1/soc/axil_sram_t28.v
../../../design/cpu_m1/soc/cpu_m1_asic_top.v
/home/edauser/project/SOC/Magpie_X3/core_ip/soc/tsmc28/sram/sky130_sram_2kbyte_1rw1r_32x512_8.v
