// =============================================================================
// tb_mat_engine.v — ADR-0037 gate_45: unit-level bit-exactness vs mat_golden.py.
// Part 1: 90 rescale corners (acc poked directly into bank 0 element 0; every
//         (acc, mult, shift, zp, clamp) line's byte 0 must equal the golden).
// Part 2: 24 random sequences (CLR -> OP(rpt) with a/b from the stub TCM ->
//         RESCALE) — all 64 output bytes must equal the golden line.
// Vector files are generated by IP/npu/golden/mat_golden.py --emit (checked in).
// =============================================================================
`default_nettype none
`timescale 1ns/1ps

module tb_mat_engine;
    reg clk = 1'b0;
    reg resetn = 1'b0;
    always #5 clk = ~clk;

    reg         go = 0;
    reg  [2:0]  cmd = 0;
    reg  [3:0]  arg_bank = 0;
    reg  [7:0]  arg_rpt = 0;
    reg  [31:0] a_addr = 0, b_addr = 0, rs_mult = 0, out_base = 0;
    reg  [7:0]  rs_shift = 0, rs_zp = 0, rs_min = 0, rs_max = 0;
    wire        busy, done, err_param;
    wire        t_we;
    wire [9:0]  t_a_addr, t_b_addr, t_waddr;
    wire [31:0] t_wdata;

    reg [31:0] mem [0:1023];
    wire [255:0] t_a_rdata, t_b_rdata;
    genvar gw;
    generate
        for (gw = 0; gw < 8; gw = gw + 1) begin : g_wide
            assign t_a_rdata[gw*32 +: 32] = mem[t_a_addr + gw[9:0]];
            assign t_b_rdata[gw*32 +: 32] = mem[t_b_addr + gw[9:0]];
        end
    endgenerate
    always @(posedge clk) if (t_we) mem[t_waddr] <= t_wdata;

    mat_engine #(.TCM_AW(10)) dut (
        .clk(clk), .resetn(resetn),
        .go(go), .abort_i(1'b0), .cmd(cmd), .arg_bank(arg_bank), .arg_rpt(arg_rpt),
        .a_addr(a_addr), .b_addr(b_addr),
        .rs_mult(rs_mult), .rs_shift(rs_shift), .rs_zp(rs_zp),
        .rs_min(rs_min), .rs_max(rs_max), .out_base(out_base),
        .busy(busy), .done(done), .err_param(err_param),
        .t_a_addr(t_a_addr), .t_a_rdata(t_a_rdata),
        .t_b_addr(t_b_addr), .t_b_rdata(t_b_rdata),
        .t_we(t_we), .t_waddr(t_waddr), .t_wdata(t_wdata)
    );

    integer errors = 0, checks = 0;

    integer go_cycles;
    task pulse_go;
        integer guard;
        begin
            @(negedge clk); go = 1'b1;
            @(negedge clk); go = 1'b0;
            guard = 0;
            while (!done && guard < 5000) begin @(posedge clk); guard = guard + 1; end
            if (!done) begin errors = errors + 1; $display("  FAIL: engine timeout"); end
            go_cycles = guard;
        end
    endtask

    task chk8(input [7:0] got, input [7:0] exp, input integer tag);
        begin
            checks = checks + 1;
            if (got !== exp) begin
                errors = errors + 1;
                $display("  FAIL case %0d: got %02x exp %02x", tag, got, exp);
            end
        end
    endtask

    integer fin, fexp, rc, i, k, n;
    integer parse_ok;
    reg [31:0] c_acc; reg [31:0] c_mult;
    integer c_sh, c_zp, c_min, c_max, c_exp;
    integer rpt_v; reg [31:0] mult_v; integer sh_v, zp_v;
    integer byte_v; reg [7:0] exp_str [0:63];
    reg [8*130-1:0] expline;

    initial begin
        $display("TB: start");
        repeat (4) @(posedge clk);
        resetn = 1'b1;
        @(posedge clk);
        $display("TB: reset done");

        // ---------- Part 1: rescale corners ----------
        fin  = $fopen("vectors/rescale_cases.txt", "r");
        fexp = $fopen("vectors/rescale_expected.txt", "r");
        if (fin == 0 || fexp == 0) begin
            $display("MAT_ENGINE_FAIL: vector files missing"); $finish;
        end
        n = 0;
        parse_ok = 1;
        while (!$feof(fin) && parse_ok) begin
            rc = $fscanf(fin, "%h %h %h %h %h %h\n", c_acc, c_mult, c_sh, c_zp, c_min, c_max);
            if (rc != 6) parse_ok = 0;
            if (rc == 6) begin
                rc = $fscanf(fexp, "%h\n", c_exp);
                dut.acc[0][0] = c_acc;                      // unit-level poke
                cmd = 3'd2; arg_bank = 4'd0;
                rs_mult = c_mult; rs_shift = c_sh[7:0];
                rs_zp = c_zp[7:0]; rs_min = c_min[7:0]; rs_max = c_max[7:0];
                out_base = 32'h0000_0C00;
                pulse_go();
                if (n == 0) $display("TB: first rescale done");
                chk8(mem[10'h300][7:0], c_exp[7:0], n);
                n = n + 1;
            end
        end
        $fclose(fin); $fclose(fexp);
        $display("part1: %0d rescale corners", n);

        // ---------- Part 2: op sequences ----------
        fin  = $fopen("vectors/seq_cases.txt", "r");
        fexp = $fopen("vectors/seq_expected.txt", "r");
        n = 0;
        parse_ok = 1;
        while (!$feof(fin) && parse_ok) begin
            rc = $fscanf(fin, "%h %h %h %h", rpt_v, mult_v, sh_v, zp_v);
            if (rc != 4) parse_ok = 0;
            if (rc == 4) begin
                // a bytes then b bytes (8*rpt each) -> stub TCM @0x000 / @0x200
                for (i = 0; i < 2 * rpt_v; i = i + 1) begin
                    mem[i] = 32'h0;
                    for (k = 0; k < 4; k = k + 1) begin
                        rc = $fscanf(fin, "%h", byte_v);
                        mem[i][k*8 +: 8] = byte_v[7:0];
                    end
                end
                for (i = 0; i < 2 * rpt_v; i = i + 1) begin
                    mem[128 + i] = 32'h0;
                    for (k = 0; k < 4; k = k + 1) begin
                        rc = $fscanf(fin, "%h", byte_v);
                        mem[128 + i][k*8 +: 8] = byte_v[7:0];
                    end
                end
                rc = $fscanf(fexp, "%s\n", expline);
                for (i = 0; i < 64; i = i + 1) begin
                    exp_str[i][7:4] = hex1(expline[8*(128 - 2*i) - 1 -: 8]);
                    exp_str[i][3:0] = hex1(expline[8*(127 - 2*i) - 1 -: 8]);
                end
                // CLR all banks
                cmd = 3'd0; arg_bank = 4'hF; pulse_go();
                // OP
                cmd = 3'd1; arg_bank = 4'd0; arg_rpt = rpt_v[7:0];
                a_addr = 32'h0; b_addr = 32'h200;
                pulse_go();
                // RESCALE
                cmd = 3'd2; rs_mult = mult_v; rs_shift = sh_v[7:0];
                rs_zp = zp_v[7:0]; rs_min = 8'h80; rs_max = 8'h7F;
                out_base = 32'h0000_0C00;
                pulse_go();
                for (i = 0; i < 64; i = i + 1)
                    chk8(mem[10'h300 + i[7:2]][(i%4)*8 +: 8], exp_str[i], 1000 + n*100 + i);
                n = n + 1;
            end
        end
        $fclose(fin); $fclose(fexp);
        $display("part2: %0d sequences", n);

        // ---------- throughput + tail known-answer (ADR-0040 guards) ----------
        // a=3, b=5 everywhere -> acc = 15*rpt exactly; RESCALE mult=0.5 shift=35
        // gives 30 for rpt=64 and 31 for rpt=65 - a broken tail mask (extra or
        // missing lanes) lands on a different byte (Codex review adoption).
        // Cycles: GO->done <= ceil(rpt/4) + 6 shell; rpt=65 forces the tail.
        for (i = 0; i < 132; i = i + 1) begin
            mem[i] = 32'h03030303;
            mem[256 + i] = 32'h05050505;
        end
        cmd = 3'd0; arg_bank = 4'hF; pulse_go();
        cmd = 3'd1; arg_bank = 4'd0; arg_rpt = 8'd64; a_addr = 32'h0; b_addr = 32'h400;
        pulse_go();
        checks = checks + 1;
        if (go_cycles > 16 + 6) begin
            errors = errors + 1;
            $display("  FAIL throughput rpt=64: %0d cycles (limit 22)", go_cycles);
        end
        $display("throughput rpt=64: %0d cycles", go_cycles);
        cmd = 3'd2; rs_mult = 32'h4000_0000; rs_shift = 8'd35; rs_zp = 8'd0;
        rs_min = 8'h80; rs_max = 8'h7F; out_base = 32'h0000_0C00;
        pulse_go();
        for (i = 0; i < 16; i = i + 1)
            chk8(mem[10'h300 + i][7:0], 8'd30, 2900 + i);
        cmd = 3'd0; arg_bank = 4'hF; pulse_go();
        cmd = 3'd1; arg_bank = 4'd0; arg_rpt = 8'd65; pulse_go();
        checks = checks + 1;
        if (go_cycles > 17 + 6) begin
            errors = errors + 1;
            $display("  FAIL throughput rpt=65: %0d cycles (limit 23)", go_cycles);
        end
        $display("throughput rpt=65: %0d cycles", go_cycles);
        cmd = 3'd2; pulse_go();
        for (i = 0; i < 16; i = i + 1)
            chk8(mem[10'h300 + i][7:0], 8'd31, 2950 + i);

        // ---------- param errors ----------
        cmd = 3'd1; arg_bank = 4'd4; arg_rpt = 8'd1; a_addr = 0; b_addr = 0;
        pulse_go();
        checks = checks + 1;
        if (!err_param) begin errors = errors + 1; $display("  FAIL: bank>=4 not flagged"); end
        cmd = 3'd2; arg_bank = 4'd0; rs_shift = 8'd30;
        pulse_go();
        checks = checks + 1;
        if (!err_param) begin errors = errors + 1; $display("  FAIL: shift<31 not flagged"); end
        cmd = 3'd1; arg_bank = 4'd0; arg_rpt = 8'd0;
        pulse_go();
        checks = checks + 1;
        if (!err_param) begin errors = errors + 1; $display("  FAIL: rpt=0 not flagged"); end
        // ADR-0040: 32B alignment now enforced (banked-SRAM honesty)
        cmd = 3'd1; arg_rpt = 8'd1; a_addr = 32'h10; b_addr = 32'h200;
        pulse_go();
        checks = checks + 1;
        if (!err_param) begin errors = errors + 1; $display("  FAIL: a 32B-align not flagged"); end
        cmd = 3'd3; arg_bank = 4'd0; a_addr = 32'h24;
        pulse_go();
        checks = checks + 1;
        if (!err_param) begin errors = errors + 1; $display("  FAIL: loadacc align not flagged"); end
        a_addr = 32'h0;

        $display("MAT_ENGINE: %0d checks, %0d errors", checks, errors);
        if (errors == 0) $display("MAT_ENGINE_PASS");
        else             $display("MAT_ENGINE_FAIL");
        $finish;
    end

    function [3:0] hex1(input [7:0] ch);
        begin
            if (ch >= "0" && ch <= "9")      hex1 = ch - "0";
            else if (ch >= "a" && ch <= "f") hex1 = ch - "a" + 4'd10;
            else                             hex1 = ch - "A" + 4'd10;
        end
    endfunction

    initial begin
        #20000000;
        $display("MAT_ENGINE_FAIL: timeout");
        $finish;
    end
endmodule
`default_nettype wire
