+incdir+IP/cpu_m1/rtl
+incdir+IP/npu/rtl
IP/npu/rtl/npu_top.v
IP/npu/rtl/npu_axil_regs.v
IP/npu/rtl/npu_dma.v
IP/npu/rtl/npu_tcm.v
IP/npu/rtl/axil_decerr.v
IP/cpu_m1/rtl/def.vh
IP/cpu_m1/rtl/rfu.v
IP/cpu_m1/rtl/alu.v
IP/cpu_m1/rtl/idu.v
IP/cpu_m1/rtl/ifu.v
IP/cpu_m1/rtl/lsu.v
IP/cpu_m1/rtl/csr.v
IP/cpu_m1/rtl/trigger.v
IP/cpu_m1/rtl/mul.v
IP/cpu_m1/rtl/div.v
IP/cpu_m1/rtl/forward.v
IP/cpu_m1/rtl/hazard.v
IP/cpu_m1/rtl/bp.v
IP/cpu_m1/rtl/ras.v
IP/cpu_m1/rtl/cdec.v
IP/cpu_m1/rtl/bmu.v
IP/cpu_m1/rtl/pmp.v
IP/cpu_m1/rtl/core.v
IP/cpu_m1/rtl/cpu_m1_top.v
IP/npu/dv/tb/axi_full_rwmem.v
IP/npu/dv/tb/tb_npu_cq_smoke.v
