"""gate_03_14_msip_directed_lockstep - msip software-interrupt directed lockstep (Tier-2 blocker #4b).

Closes blocker #4b's LOCKSTEP-ABLE path. msip (CLINT M software interrupt, ADR-0019) is the
deterministic interrupt: the program decides exactly when it becomes pending, so the DUT and Spike
agree on the pre-IRQ commit prefix (truly-async meip/mtip cannot be per-commit lockstepped — Spike has
no matching async injection, so they stay directed-only).

Correctness is proven the same way as the through-trap slice (gate_03_12):
  (1) Spike per-commit lockstep on the PRE-IRQ prefix, and
  (2) the DUT executing the full handler with trap CSRs matched to the RISC-V Priv spec
      (mcause==0x8000_0003 M-software-int, mepc==0x82, mstatus==0x1880 MPP=M/MPIE=1, resume==0x600d).

The phase also builds with --coverage; the island demonstrably toggles the msip IRQ-path bits in u_csr
(msip / irq_msi / irq_pending / mie_msie / mip[3] / irq_cause-MSW / mcause), i.e. those "IRQ-sourced"
toggle bits are reachable. (Per-island, not farm-merged: a distinct TB top has a distinct coverage
hierarchy, so cross-TB union is unsound — see docs/reports/coverage_report.md §2.11.)
"""

import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
PHASE = ROOT / "flow/v2_pipeline/phase_03_14_msip_directed"


def _read(name: str) -> str:
    return (PHASE / name).read_text(encoding="utf-8")


def test_phase_03_14_artifacts_exist():
    # Committed durable evidence (build outputs like coverage.dat / *.trace / wave.vcd are
    # .gitignore'd and regenerated by `make`, so they are not required here).
    for name in ["firmware.S", "firmware.lds", "firmware_spike.lds", "Makefile",
                 "tb_msip_directed.v", "msip_directed.py", "firmware.hex",
                 "sim.log", "spike.log", "msip_directed.log"]:
        p = PHASE / name
        assert p.exists() and p.stat().st_size > 0, f"missing/empty artifact: {name}"


def test_phase_03_14_program_enables_msie_and_handles_msw():
    # Read the COMMITTED source (firmware.S), not firmware.disasm — the disasm is a .gitignore'd
    # build output, absent in a fresh clone (caught by the M1A fork smoke run).
    src = _read("firmware.S")
    assert re.search(r"csrs\s+mie", src), "must enable MIE.MSIE (csrs mie)"
    assert re.search(r"csrr\s+\w+,\s*mcause", src), "handler must read mcause"
    assert re.search(r"\bmret\b", src), "handler must mret"


def test_phase_03_14_sim_asserts_msip_and_passes():
    sim = _read("sim.log")
    assert "FAIL" not in sim, f"sim reported FAIL: {sim!r}"
    assert "assert msip" in sim, "TB did not assert msip"
    assert sim.strip().splitlines()[-1].startswith("PASS") or any(
        l.startswith("PASS") for l in sim.splitlines()), "sim did not PASS"


def test_phase_03_14_lockstep_pass_with_msw_cause():
    log = _read("msip_directed.log")
    assert log.lstrip().startswith("PASS"), f"msip lockstep not PASS: {log!r}"
    assert "prefix lockstep matched" in log
    assert "0x80000003" in log, "handler mcause must be the M-software-interrupt cause"


def test_phase_03_14_coverage_toggles_msip_irq_path():
    """The coverage island must show the msip IRQ-path bits in u_csr toggling (reachability).
    coverage.dat is a build output (.gitignore'd); skip if the phase has not been built."""
    cov = PHASE / "coverage.dat"
    if not (cov.exists() and cov.stat().st_size > 0):
        pytest.skip("coverage.dat not built (run `make` in phase_03_14_msip_directed)")
    hits = {}
    for line in _read("coverage.dat").splitlines():
        m = re.match(r"^C '(.*)' (\d+)\s*$", line)
        if not m:
            continue
        key, cnt = m.group(1), int(m.group(2))
        fld = dict((x[0], x.split("\002", 1)[1]) for x in key.split("\001") if "\002" in x)
        if fld.get("t") != "toggle" or fld.get("h", "").split(".")[-1] != "u_csr":
            continue
        base = re.sub(r"\[.*", "", fld.get("o", "?")).split(":")[0]
        if cnt > 0:
            hits[base] = hits.get(base, 0) + 1
    for sig in ("msip", "irq_msi", "irq_pending", "mie_msie"):
        assert hits.get(sig, 0) > 0, f"msip IRQ-path signal {sig} did not toggle in the island"
